# Generated by Django 5.2.3 on 2025-06-22 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='description',
            field=models.TextField(default='Decricao do jogo', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='price',
            field=models.FloatField(default=19.9),
            preserve_default=False,
        ),
    ]
