# Generated by Django 5.2.3 on 2025-06-23 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_game_description_game_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='game/images'),
            preserve_default=False,
        ),
    ]
